# Generated by Django 5.1.1 on 2024-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='', verbose_name='Icon'),
        ),
    ]
