# Generated by Django 5.1.1 on 2024-10-30 14:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rename_image, verbose_name='Icon'),
        ),
    ]
