# Generated by Django 5.1.1 on 2024-11-06 22:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Introduction'),
        ),
    ]
