# Generated by Django 5.1.1 on 2024-09-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo2'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo3'),
        ),
    ]
