# Generated by Django 5.1.1 on 2024-10-12 04:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_photo2_blogpost_photo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.rename_image, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.rename_image, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.rename_image, verbose_name='Photo3'),
        ),
    ]
