# Generated by Django 5.1.1 on 2024-10-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='public content?'),
        ),
    ]
