# Generated by Django 5.1.1 on 2024-11-03 21:05

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='Comment'),
        ),
    ]
