# Generated by Django 5.1.1 on 2024-11-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_good_good_to_gooder_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Blog Post'),
        ),
    ]
