# Generated by Django 5.1.1 on 2024-11-10 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_to2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods2', to='blog.comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='blog.blogpost', verbose_name='Blog Post'),
        ),
        migrations.AddConstraint(
            model_name='good',
            constraint=models.UniqueConstraint(fields=('good_to2_id', 'gooder_id'), name='good_to2_gooder_unique'),
        ),
    ]
