# Generated by Django 5.1.1 on 2024-11-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like_delete_good_like_blogpost_user_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_blogposts', to='blog.blogpost', verbose_name='Blog Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_comments', to='blog.comment', verbose_name='Comment'),
        ),
    ]
