# Generated by Django 5.1.1 on 2024-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpost_only_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='only_friends',
            field=models.BooleanField(default=False, verbose_name='only-friends content?'),
        ),
    ]
