# Generated by Django 5.1.1 on 2024-11-27 09:30

from django.db import migrations


def alter_only_friends(apps, schema_editor):
    BlogPost = apps.get_model("blog", "BlogPost")
    for blogpost in BlogPost.objects.all():
        blogpost.only_friends = False
        blogpost.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpost_only_friends'),
    ]

    operations = [
        migrations.RunPython(alter_only_friends),
    ]
