# Generated by Django 5.1.1 on 2025-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_clientip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientip',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='City'),
        ),
    ]
