# Generated by Django 5.1.1 on 2025-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_clientip_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientip',
            name='country_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='clientip',
            name='country_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country Name'),
        ),
    ]
