# Generated by Django 5.1.1 on 2025-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_clientip_country_code_clientip_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientip',
            name='page',
            field=models.CharField(max_length=511, verbose_name='Access Page'),
        ),
    ]
